name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on:
  push:
    branches:
    - main

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
            node-version: '18.x'
      - name: Install the site dependencies
        run: npm install
      - name: Build the site static assets
        run: npm run build
      - name: Build the site static assets
        run: ls -lan
